---
# This repository only supports Palette SaaS central agent mode installs.
palette_management_mode: central
palette_endpoint: api.spectrocloud.com
palette_project_name: Default
palette_use_fips: false
palette_vip_skip: false

palette_http_proxy: ""
palette_https_proxy: ""
palette_install_workdir: /opt/palette-agent
palette_reboot_after_install: true
palette_reboot_timeout: 1800

palette_external_registries: []
palette_registry_mapping_rules: {}

palette_site_extra: {}
palette_stylus_extra: {}

palette_configure_cilium_firewalld: false
palette_cilium_firewalld_zone: public
